apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: iris
spec:
  licenseKeySecret:
    name: iris-license
  topology:
    data:
      image: quay.io/jkeam1/secured-rest-api@sha256:5c6e986c7405464aede90d8122b869c1123ef45d659283ab405a93451229d0c1
      podTemplate:
        spec:
          args:
          - --check-caps
          - "false"
        readinessProbe:
          httpGet:
            path: /
            port: 52773
          initialDelaySeconds: 30
          periodSeconds: 10
