apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: iris
spec:
  licenseKeySecret:
    name: iris-license
  topology:
    data:
      image: quay.io/jkeam1/secured-rest-api@sha256:aa39f9ea3909b317b4fca8eae8eefdb9864b93744e3ea6dbed91e91cb0e476e6
      podTemplate:
        spec:
          args:
          - --check-caps
          - "false"
        readinessProbe:
          httpGet:
            path: /
            port: 52773
          initialDelaySeconds: 30
          periodSeconds: 10
